title: Hana Archive
description: Places I went, archive entries, scans, and photos.
baseurl: "/hana_archive"

collections:
  locations:
    output: true
    permalink: /locations/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: entry
  - scope:
      path: ""
      type: "locations"
    values:
      layout: location

markdown: kramdown